### ISSUE TITLE
keyword to remove N and S

### ISSUE THREAD

**Issue by lazarusA** [MakieOrg/GeoMakie.jl#112]
is there a key argument to remove the N and S from the tick labels? +- is enough IMHO.

**Comment by visr** [comment]
It should be either N and S or + and - I think. Right now it's only N and S, we discussed it briefly here: https://github.com/JuliaPlots/GeoMakie.jl/pull/103#issuecomment-1117429543

**Comment by asinghvi17** [comment]
You can set the tick labe formatter to `GeoMakie.geoformat_ticklabels`
