### ISSUE TITLE
Frame lines are cut off

### ISSUE THREAD

**Issue by jkrumbiegel** [MakieOrg/GeoMakie.jl#145]
I guess you're all aware of that, but all the frame lines of the geo-axes are cut off where they lie on the edge of the axis scene. I only briefly skimmed the code and noticed you're actually using `Axis` in the backend in some pirate-y way :) Axis itself plots the axis lines and ticklabels etc into the `blockscene` not the `scene` because the `blockscene` always extends fully over the scene of the parent object (if that's the Figure, then the whole Figure). This way, I avoid cutting off anything halfway. The only thing is that the `blockscene` is pixel-projected, so everything going in there needs preprojection.

Examples:

<img width="363" alt="grafik" src="https://user-images.githubusercontent.com/22495855/212406231-f137f739-e2e4-4a83-82c2-fae1f78267ec.png">

<img width="402" alt="grafik" src="https://user-images.githubusercontent.com/22495855/212406305-b84bfc37-573b-4fac-a179-0b14d48d7e3b.png">

<img width="477" alt="grafik" src="https://user-images.githubusercontent.com/22495855/212406345-28b9eba4-71a9-45ef-8697-c2c2212bd7e5.png">

**Comment by asinghvi17** [comment]
Good point - thanks for highlighting that!  Was a quick fix so will push it with the rest of the changes once I've tested them.
