### ISSUE TITLE
Higher resolution coastlines?

### ISSUE THREAD

**Issue by Balinus** [MakieOrg/GeoMakie.jl#159]
Hello!

I was wondering if there was a way to add higher resolution coastlines and what would be the best approach to do it?

Cheers!

**Comment by asinghvi17** [comment]
I'm working on a package to provide that!  For now you could access e.g. the 1:10m coastlines from NaturalEarth, and plot that.

**Comment by Balinus** [comment]
The 1:10m coastlines is the one when we use the `coastlines=true` in a `GeoAxis` ?

**Comment by asinghvi17** [comment]
https://www.naturalearthdata.com/http//www.naturalearthdata.com/download/10m/physical/ne_10m_coastline.zip

www.naturalearthdata.com

**Comment by Balinus** [comment]
ok, thanks! I will take a look and see how I can plot it with GeoMakie. 

Cheers!

**Comment by asinghvi17** [comment]
Nice, that works!

For future reference, the package I mentioned earlier was https://github.com/JuliaGeo/NaturalEarth.jl.  You can also get GeoJSON from http://github.com/nvkelso/natural-earth-vector, in the `geojson` folder.  That's what NaturalEarth.jl extracts.
