### ISSUE TITLE
make grid invisible

### ISSUE THREAD

**Issue by filchristou** [MakieOrg/GeoMakie.jl#167]
Hi. I would like to make the grid invisible. I tried it with the standard Makie commands in the italian map:
```julia
let
	it_states = Downloads.download("https://github.com/openpolis/geojson-italy/raw/master/geojson/limits_IT_provinces.geojson")
	geo = GeoJSON.read(read(it_states, String))
	
	fig = Figure()
	ga = GeoAxis(fig[1, 1]; dest = "+proj=ortho +lon_0=12.5 +lat_0=42", lonlims=(12, 13), latlims = (40, 44), xgridvisible=false, ygridvisible=false, xticklabelsvisible=false, yticklabelsvisible=false, xticksvisible=false, yticksvisible=false)
	poly!(ga, geo; strokecolor = :blue, strokewidth = 1, color = (:blue, 0.5), shading = false);
	datalims!(ga)
	
	fig
end
```
![image](https://user-images.githubusercontent.com/27723218/235207639-695d46c6-bbd7-4895-a1cc-8870c4e6605c.png)
it works for ticks and labels but not for the grid.

**Comment by filchristou** [comment]
I want to mention that `hidedecorations!(ga)` is working.

**Comment by melioristic** [comment]
I have the same issue. Would like to know if a solution exists.

**Comment by noahrhodes** [comment]
I use this to hide the grid and labels
```julia
hidedecorations!(ga)
hidespines!(ga)
```

**Comment by asinghvi17** [comment]
Should work now, the API is significantly different as well.
