### ISSUE TITLE
wrong coordinate transformation ? German lakes

### ISSUE THREAD

**Issue by filchristou** [MakieOrg/GeoMakie.jl#168]
Hi, the following figure is supposed to produce the map of germany with the lakes.
```julia
let
	geoger = GeoJSON.read(read(Downloads.download("https://raw.githubusercontent.com/isellsoap/deutschlandGeoJSON/main/2_bundeslaender/4_niedrig.geo.json"), String))
	lakes = GeoJSON.read(read(Downloads.download("https://raw.githubusercontent.com/nvkelso/natural-earth-vector/master/geojson/ne_10m_lakes_europe.geojson"), String))

	fig = Figure()
	ga = GeoAxis(fig[1, 1]; dest = "+proj=merc", lonlims=(11, 13), latlims = (30, 44))

	poly!(ga, geoger; strokewidth = 1, color=:gold, rasterize = 5)
	poly!(ga, lakes; strokewidth = 1, color=:blue, rasterize = 5,  xautolimits=false, yautolimits=false)
	datalims!(ga)

	fig
end
```
![image](https://user-images.githubusercontent.com/27723218/235212076-19c9ef74-f2e9-4d4e-91ea-0de53ed34683.png)

However lakes are not like that in Germany: https://www.stepmap.de/landkarte/seen-in-deutschland-kItU9UMxoG-i
![image](https://user-images.githubusercontent.com/27723218/235212251-c534b4b8-9e41-4641-96c4-8fe41e0d7925.png)

Did I make a mistake somewhere, or is there a bug  ?

**Comment by asinghvi17** [comment]
There is a bug in the current implementation.  That bug is, as I understand, that the aspect ratio of the scene is determined by the limits before the transformation (in lat/long space) and not after it.   The big refactor for GeoMakie should fix all this...will see if there can be some kind of quick fix for this!

**Comment by asinghvi17** [comment]
![download-5](https://github.com/MakieOrg/GeoMakie.jl/assets/32143268/72829a7d-472c-4406-b533-f131373672ad)
Latest version should fix this!

**Comment by filchristou** [comment]
How is this fixed ? In the documentation it's also wrong. https://geo.makie.org/v0.7.2/examples/german_lakes

**Comment by asinghvi17** [comment]
Ah, just to confirm - is the error in the actual lake positions or the aspect ratio?  The lake positions are probably fixable by using a better dataset but the aspect ratio was the main bug IMO.

**Comment by asinghvi17** [comment]
Ah, the dataset you linked to is not the dataset used in the example (which is really weird on reflection, I should change that to NaturalEarth).  Looking at the one from the example I have no idea what it's actually showing 😅.
