### ISSUE TITLE
Use the proj C-API to avoid errors being thrown in Julia

### ISSUE THREAD

**Issue by asinghvi17** [MakieOrg/GeoMakie.jl#170]
When Proj has an error, you can enquire using a ccall, meaning that we don't need to wrap each point transform in a try-catch block!

**Comment by visr** [comment]
Is the error handler an issue? See also https://github.com/JuliaGeo/GDAL.jl/pull/153

**Comment by asinghvi17** [comment]
I think this works now, haven't had any bad experiences this far.
