### ISSUE TITLE
`fig` doesn't display in Pluto notebook

### ISSUE THREAD

**Issue by SimonEnsemble** [MakieOrg/GeoMakie.jl#175]
# the issue
figure doesn't display in Pluto upon minimal example
```julia
fig = Figure()
ga = GeoAxis(
	  fig[1, 1]; # any cell of the figure's layout
	  dest = "+proj=wintri", # the CRS in which you want to plot
	  coastlines = true # plot coastlines from Natural Earth, as a reference.
)
scatter!(ga, -120:15:120, -60:7.5:60; color = -60:7.5:60, strokecolor = (:black, 0.2))
fig
```

<img width="809" alt="Screenshot 2023-08-04 at 3 45 50 PM" src="https://github.com/MakieOrg/GeoMakie.jl/assets/30643894/579d8993-3fb8-4261-a86c-8d239c23f74e">

# version info
`GeoMakie` v0.5.1
`Pluto` v0.19.27

Julia Version 1.9.2
Commit e4ee485e909 (2023-07-05 09:39 UTC)
Platform Info:
  OS: macOS (arm64-apple-darwin22.4.0)
  CPU: 8 × Apple M1
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-14.0.6 (ORCJIT, apple-m1)
  Threads: 1 on 4 virtual cores

**Comment by SimonDanisch** [comment]
which makie backend?

**Comment by SimonEnsemble** [comment]
your question made me ask "oh, is `CairoMakie` required too?"
so instead of just `using GeoMakie`, I'm now `using GeoMakie, CairoMakie` and it works.
sorry for the rookie mistake. 😞
