### ISSUE TITLE
how to join geojson  file and data like  countries  gdp

### ISSUE THREAD

**Issue by math4mad** [MakieOrg/GeoMakie.jl#189]
how to join geojson  file and data like  countries  gdp

geojson_row!=data_row

**Comment by asinghvi17** [comment]
You can convert the GeoJSON feature collection to a DataFrame (`DataFrame(fc)`) and perform a regular join from there.  This is probably not the appropriate place to ask ;) - you would get a quicker response on the Julia Discourse!
