### ISSUE TITLE
events function no longer work for GeoAxis

### ISSUE THREAD

**Issue by Zetison** [MakieOrg/GeoMakie.jl#198]
Before v0.6.0 I could get mousepositions from events(ax), but not after v0.6.0. Bug reproduced by:

`using GeoMakie; fig = Figure(); ax = GeoAxis(fig[1,1]); events(ax)`

Error message:

```
ERROR: MethodError: no method matching get_scene(::GeoAxis)

Closest candidates are:
  get_scene(::Figure)
   @ Makie C:\Users\jonv\.julia\packages\Makie\HlTTF\src\figures.jl:27
  get_scene(::Axis3)
   @ Makie C:\Users\jonv\.julia\packages\Makie\HlTTF\src\makielayout\helpers.jl:435   
  get_scene(::Makie.FigureAxisPlot)
   @ Makie C:\Users\jonv\.julia\packages\Makie\HlTTF\src\figures.jl:28
  ...

Stacktrace:
 [1] events(x::GeoAxis)
   @ Makie C:\Users\jonv\.julia\packages\Makie\HlTTF\src\scenes.jl:490
 [2] top-level scope
   @ REPL[43]:1
```

This still works fine with Makie.Axis:

`using GLMakie; fig = Figure(); ax = Axis(fig[1,1]); events(ax)`

**Comment by asinghvi17** [comment]
Try running `Makie.get_scene(ga::GeoMakie.GeoAxis) = ga.scene` and try again?  Will include this in the next release.

**Comment by Zetison** [comment]
> Try running `Makie.get_scene(ga::GeoMakie.GeoAxis) = ga.scene` and try again? Will include this in the next release.

Yes, that seems to work
