### ISSUE TITLE
ax.finallimits[] not updated after calling limits!(ax, ...)

### ISSUE THREAD

**Issue by Zetison** [MakieOrg/GeoMakie.jl#202]
A bug for `v0.6.1` can be reproduced by

`using GLMakie, GeoMakie; fig = Figure(); layout = fig[1,1] = GridLayout(); ax = GeoMakie.GeoAxis(layout[1,1], source="+proj=merc", dest="+proj=merc"); text!(ax,0.0,0.0,text="test"); limits!(ax,[-1.0, 2.5],[-2.0, 2.0]); println(ax.finallimits[].widths); display(fig)`

which returns `[3.499999729683623e-5, 3.9999998989515007e-5]` instead of `[3.5, 4.0]` (for some reason a multiplication of a factor 1e-5 has occured). The same issue for `ax.finallimits[].origin`

**Comment by asinghvi17** [comment]
#207 should fix this.  That was expected behaviour earlier, the reason is that Makie used to run only on Float32, so we rescaled projections by `100_000` so that there was still enough float precision to do things.  With #207 all computations are in Float64 which is substantially better.
