### ISSUE TITLE
GeoAxis not defined

### ISSUE THREAD

**Issue by PashHas** [MakieOrg/GeoMakie.jl#203]
I have GeoMakie 0.6.1, and when I try to plot the examples codes. I get "ERROR: LoadError: UndefVarError: `GeoAxis` not defined". I tried GeoMakie.Axis, then as expected the projections dont work.

**Comment by asinghvi17** [comment]
Huh, that's strange.  It works fine for me.

Two possibilities come to mind:
1. What is the output of `GeoMakie.GeoAxis`?
2. Do you have something else named `GeoAxis` in your namespace?  A way to check this would be to restart your session of Julia, thus removing all current variables.

**Comment by PashHas** [comment]
Thank you, this is what I get after restarting Julia session. 

> julia> Pkg.status("GeoMakie")
> Status `~/.julia/environments/v1.10/Project.toml`
>   [db073c08] GeoMakie v0.6.1
> 
> julia> GeoMakie.GeoAxis()
> ERROR: UndefVarError: `GeoMakie` not defined
> Stacktrace:
>  [1] top-level scope
>    @ REPL[47]:1

**Comment by asinghvi17** [comment]
Closing as stale, please let me know if the issue persists and I'll reopen it.
