### ISSUE TITLE
Examples from README don't work

### ISSUE THREAD

**Issue by jfb-h** [MakieOrg/GeoMakie.jl#204]
When I run the quickstart example in the README I get `ERROR: MethodError: no method matching initialize_block!(::GeoAxis; coastlines::Bool)`. Similarly, the `lonlims` argument also seems to not work anymore. I'm running `v0.6.1`, have these been replaced recently?

**Comment by asinghvi17** [comment]
Thanks for catching that!  They have - the basic example in the docs is the way to go now.  Coastlines is replaced by calling `lines!(ax, GeoMakie.coastlines())`, and the limits are x and y instead of lon and lat respectively.

Will fix this soon!

**Comment by jfb-h** [comment]
Thanks for the quick fix!
