### ISSUE TITLE
High Latitude data over a range smaller than a hemisphere

### ISSUE THREAD

**Issue by jsbyrnes** [MakieOrg/GeoMakie.jl#210]
I am trying to plot a contour of data from lon (-120.979, 101.12), lat (52.124, 87.382). 

The documentation has an example of how to use an orthographic projection with strict lon,lat limits but also flags this as not consistent with the current API. I have also tried a mercator projection with a higher central latitude, but etc +proj=merc + lat_0=65 didn't change anything. Do these features still/will exist in the new API, or is there a simple way to do this I am just missing?

**Comment by asinghvi17** [comment]
The Germany documentation example in the docs should clear this up!

https://geo.makie.org/dev/examples/german_lakes
