### ISSUE TITLE
UTM Projections

### ISSUE THREAD

**Issue by consumere** [MakieOrg/GeoMakie.jl#214]
I tried to transform to a UTM projection.

`prj = "+proj=utm +zone=32 +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs"`
`fig = GeoMakie.Figure();`
`ax = GeoMakie.GeoAxis(fig[1,1],
    dest=prj,
    title="UTM 32";)`
`lp = lines!(ax, GeoMakie.coastlines(); 
    transformation = (; translation = (0, 0, 1)))`

This is what i get:

![utm](https://github.com/MakieOrg/GeoMakie.jl/assets/51954603/2cae9ba6-9a70-48d9-b679-a7a76c39e48b)

**Comment by asinghvi17** [comment]
I can replicate that.  For UTM projections you probably want to restrict the projection to that particular zone though?  And you can restrict latitudes to (-90, 90).

**Comment by consumere** [comment]
Yes, i was wondering, if it wouldnt be much effort to implemnt this kind of transformations, since GeoMakie already uses proj strings.

[https://proj4.org/en/9.4/operations/projections/utm.html](url)

**Comment by asinghvi17** [comment]
You are already using those, no?  It's just a matter of passing the correct limits to GeoAxis then.

**Comment by consumere** [comment]
No, i would expect a grid with X and Y coordinates.
Like this:
```
import ArchGDAL
srccrs = "+proj=longlat +datum=WGS84 +no_defs"
destcrs = "+proj=utm +zone=32 +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs"
xc,yc = 11.5, 50.5
pt = ArchGDAL.createpoint(xc,yc)
#Geometry: POINT (11.5 50.5)
ArchGDAL.reproject(pt,
    ProjString(srccrs),
    ProjString(destcrs)
    )
#Geometry: POINT (677291.966065446 5597210.83026226)
```

**Comment by asinghvi17** [comment]
Ah, for that you can plot in a regular Makie axis!  You would have to explicitly reproject your geometries, though.

**Comment by consumere** [comment]
Got it, thanks... so no internal Raster transformation. for example.
this works. 
```
r isa Raster 
#true
#already utm
import Makie
fig = GeoMakie.Figure();
ax =  Makie.Axis(fig[1,1],title="UTM 32";)
rsf = GeoMakie.heatmap!(ax,r;)
fig
```

**Comment by asinghvi17** [comment]
Yep this works!  The idea of GeoMakie is to be as transparent as possible with the least amount of added features - everything that works here except for (a) multiple CRS in a plot and (b) lat-long grids in any projection will work in base Makie.  Some code has actually been shifted from here to Makie.jl for that reason.
