### ISSUE TITLE
Incompatibility with GeometryBasics@0.4.11

### ISSUE THREAD

**Issue by Zetison** [MakieOrg/GeoMakie.jl#226]
It seems GeoMakie has some issues with GeometryBasics@0.4.11:

WARNING: Method definition isfinite(Union{GeometryBasics.AbstractPoint{Dim, T} where T where Dim, GeometryBasics.Vec{S, T} where T where S}) in module GeometryBasics at C:\Users\jonv\.julia\packages\GeometryBasics\ebXl0\src\fixed_arrays.jl:134 overwritten in module GeoMakie at C:\Users\jonv\.julia\packages\GeoMakie\Nvneh\src\utils.jl:128.
│  ERROR: Method overwriting is not permitted during Module precompilation. Use `__precompile__(false)` to opt-out of precompilation.

Using GeometryBasics@0.4.10 resolves this issue

**Comment by asinghvi17** [comment]
Which version are you on?  v0.6.3 of GeoMakie should not have this issue.

**Comment by vuolleko** [comment]
I have the same issue with GeoMakie@0.6.3 and GeometryBasics@0.4.11. Works fine with 0.6.2 and 0.4.10.

**Comment by asinghvi17** [comment]
Do you see the same error with v0.6.4?
