### ISSUE TITLE
Plot limits do not set automatically when `-Inf` values are present

### ISSUE THREAD

**Issue by nchisholm** [MakieOrg/GeoMakie.jl#238]
Using GeoMakie 0.6.5, I found that `GeoAxis` limits fail to set automatically if there are one or more `-Inf` values present in the data being plotted.  `+Inf`, `NaN`, or `missing` values do not trigger the issue.  I tried `heatmap` using `CairoMakie` and `surface` using `GLMakie` with similar results.

```julia
using GLMakie, GeoMakie

fig = Figure()
ga = GeoAxis(fig[1, 1])

lons = -180:180
lats = -90:90
z = [exp(cosd(l)) + 3(y/90) for l in lons, y in lats]

# One or more values to `-Inf`
@. z[-3 < lons < 3, -3 < lats < 3] = -Inf

hm = surface!(ga, lons, lats, z; shading=NoShading, interpolate=false)
```

Result:
![map](https://github.com/MakieOrg/GeoMakie.jl/assets/2267458/a1b13729-efc5-4a20-b555-96d55cd00831)

If I change `-Inf` to `Inf` or `NaN`, I get what I expect.
![map-expected](https://github.com/MakieOrg/GeoMakie.jl/assets/2267458/6ff148ed-f203-486e-9e69-6f3fdf3b0123)

**Comment by asinghvi17** [comment]
This shouldn't be an issue on master and Makie v0.21 - am away from my laptop but will confirm later.

**Comment by asinghvi17** [comment]
This displays correctly on master, with both CairoMakie and GLMakie in png mode:
![download-2](https://github.com/MakieOrg/GeoMakie.jl/assets/32143268/22b6d6de-1a2a-455e-b963-11753f709e85)

CairoMakie in PDF is also fine, but SVG has some weird artefacts depending on which renderer you use.  That can't be helped there, though.

If you want to use GeoMakie master, 
```julia
using Pkg
Pkg.add(name = "GeoMakie", rev = "master") 
```
ought to do it.  Just remember to `Pkg.free("GeoMakie")` later.
