### ISSUE TITLE
GeoMakieDimensionalDataExt

### ISSUE THREAD

**Issue by asinghvi17** [MakieOrg/GeoMakie.jl#269]
We need to ensure that any dimensional arrays have range like lookups before we allow meshimage...if they don't we can throw an informative error redirecting the user to surface.

@rafaqz you may want to do the same for `image` in DD...

**Comment by rafaqz** [comment]
Not necessarily holding ranges... But `Regular` spans. We don't swap regular vectors to ranges to avoid the floating point changes.

But yes I wonder if an error or a warning is best

**Comment by asinghvi17** [comment]
I think we already have an error/warning now...
