### ISSUE TITLE
Convert data coordinates to pixel coordinates

### ISSUE THREAD

**Issue by aplavin** [MakieOrg/GeoMakie.jl#295]
For regular Makie axes, I've been using
```julia
fullproject(ax, p) = Makie.project(Makie.get_scene(ax), Makie.apply_transform(Makie.transform_func(ax), p)) + viewport(ax)[].origin
```
to convert from data coordinates to Figure pixel coordinates. But this function doesn't seem to work for GeoAxis, any suggestions on how to do this conversion?
For one usecase, see `MakieExtra.zoom_lines!`:
works correctly for regular axes
![Image](https://github.com/user-attachments/assets/09e1759e-37ed-401e-9df6-e69dc5eef0a7)
but not for GeoAxes
![Image](https://github.com/user-attachments/assets/f8b7d7cd-777d-4f5d-a161-a143ee0878ca)

**Comment by asinghvi17** [comment]
Hmm, looks like the problem is that `Makie.transform_func` on a GeoAxis returns `identity`.  Will push a fix up shortly.  

The fix is `Makie.transform_func(ax::GeoAxis) = ax.transform_func[]`, if you want to use this immediately.

**Comment by asinghvi17** [comment]
There could be some interesting extensions to that `zoom_lines` function (the rectangles could be in different spaces / projections) as well if you're interested in that...

**Comment by asinghvi17** [comment]
It shouldn't be too complicated...you already have the lines in `slines`, so you can simply densify ("segmentize") them using GeometryOps (or just manually).   This resampling would have to be done in the space of `ax2.finallimits`, and then the resulting points would be transformed by `ax1.transform_func`.
