### ISSUE TITLE
Projections!

### ISSUE THREAD

**Issue by natgeo-wong** [MakieOrg/GeoMakie.jl#3]
Hi!  I've just stumbled upon this (thanks to the Julia Slack for pointing me here), but are there plans to include map projections in GeoMakie?  If so how do we go about contributing (i have no experience in doing map projections, but I can try).

**Comment by SimonDanisch** [comment]
It would be lovely if we could just use some of the existing projection packages! @c42f, @evetion, @visr and @yeesian probably know more about this!

**Comment by c42f** [comment]
There's several packages for map projections. You could try Proj4.jl if you want many projections and few dependencies (though it wraps a C library and is quite close to the C API which can be a bit low level). There's the pure-julia Geodesy.jl which is also fairly focused on dealing with coordinate systems but the set of projections is very limited.

Then there's also GMT.jl and ArchGDAL.jl which are wrappers around much larger libs with a lot of functionality. (These likely use the proj C library internally; I'm pretty sure GDAL does.)

If you just want map projections and you want a wide range of functionality I'd probably suggest Proj4.jl. But I haven't used these libraries in a while so my info may be a bit out of date.

See also https://discourse.julialang.org/t/use-linear-interpolation-between-two-lla-coordinate-system-points/28296/8

**Comment by asinghvi17** [comment]
For the GeoAxis, you can supply a kwarg `crs = (source = source_proj, dest = dest_proj)`.  For all others, you need to pretransform the data, but that's easy...

**Comment by rafaqz** [comment]
If you want to extend projections to handling well known text, epsg codes etc you could depend on [GeoFormatTypes.jl](https://github.com/JuliaGeo/GeoFormatTypes.jl).

There's an almost finished [PR](https://github.com/yeesian/ArchGDAL.jl/pull/97) at ArchGDAL will allow these types to be reprojected and converted with a single command like `reproject(x, sourcecrs, destcrs)` that accepts any projection formats like well known text, proj4, epsg codes etc.
