### ISSUE TITLE
Tissot indicatrix

### ISSUE THREAD

**Issue by asinghvi17** [MakieOrg/GeoMakie.jl#5]
colors on a mesh maybe?  or deformations using decomposed circles (probably better).

**Comment by asinghvi17** [comment]
I need to implement a geodesic module for this.  @Datseris would you be willing to help?  Should be a straightforward integration to Proj's C-library (possibly using https://github.com/SciTools/cartopy/blob/master/lib/cartopy/geodesic/_geodesic.pyx as a reference as well)?

**Comment by visr** [comment]
Nice. I don't much about geodesic calculations, but can drop links as usual ;)

As mentioned on https://proj.org/geodesic.html, PROJ uses GeographicLib for this.

Interestingly GeographicLib has been ported to Julia in https://github.com/anowacki/GeographicLib.jl, and there is an open PR to incorporate this into Geodesy.jl: https://github.com/JuliaGeo/Geodesy.jl/pull/53.

**Comment by Datseris** [comment]
I can't make any promises at the moment, especially with things I am not familiar with, but in general I'll be contributing to GeoMakie.jl. I am not sure I can do much about this specific issue though, I've yet to grasp the basics...

**Comment by asinghvi17** [comment]
As it turns out, a proper Tissot indicator should really be done using great circle calculations.  There's a new example in #207 which shows how you can use Proj.jl's new geodesic API for this purpose.

Still waiting on antimeridian cutting which should come with [GeometryOps.jl](https://github.com/asinghvi17/GeometryOps.jl) fairly soon!
