### ISSUE TITLE
xyz tiles

### ISSUE THREAD

**Issue by gszep** [MakieOrg/GeoMakie.jl#67]
Any plans to have [xyz tiles](https://openlayers.org/en/latest/examples/xyz.html) being implemented in a zoom-able plot?

**Comment by visr** [comment]
Not really concrete plans, but I do think we should support basemaps. Perhaps we can further develop and integrate https://github.com/yeesian/MapTiles.jl.

**Comment by gszep** [comment]
this would be useful not only for geographic maps but also microscopy and exploration of embedded high dimensional datasets (tSNE or UMAP projections for example)

**Comment by visr** [comment]
I don't have much experience using MapTiles.jl, I just updated it yesterday. But is quite simple, it allows you to easily get images from a list of providers (or your own), based on extents and zoom levels. It doesn't have UI functions built in, only a Plots.jl plotting recipe.

> I'm wondering whether it would be easier to serve OpenLayers using JSServe.jl. Linking to OpenLayers means less code maintenance on the Julia side, but I doubt OpenLayers would work with the default GLMakie backend

It'd be good to not have to maintain more code, but I'm not sure it would be simpler in this case. Which parts would you want to use? If we can use MapTiles to fetch images, and we can hook it up to the zooming and drawing in GeoMakie, we'd be mostly there, or am I forgetting things? Caching may be nice to speed things up, but can always be added later.

**Comment by scls19fr** [comment]
Supporting MBTiles format could be a great feature to have.
See https://github.com/yeesian/MapTiles.jl/issues/11

**Comment by asinghvi17** [comment]
That's definitely something that can be done...all you would have to do is trigger an observable which changes the z-level at some zoom levels, and paste all the images together into one large image matrix.  Alternatively, instead of zoom levels, you may want to look at axis limits as a z-parameter.

**Comment by alex-s-gardner** [comment]
This would be a very powerful addition to GeoMakie.. is there any interest on moving this forward. I'm willing to help out but really don't have a ton of Julia skill to offer.

**Comment by rafaqz** [comment]
We could combine providers with [Leaflet.jl](https://github.com/JuliaGeo/Leaflet.jl/blob/main/src/providers.jl), I've recently updated them there and registered Leaflet.jl.

@alex-s-gardner probably getting MapTiles.jl better tested and registered is the first step here.

**Comment by alex-s-gardner** [comment]
I'll likely try to use MapTiles.jl for a project I'm working on so I'll see if I can make progress

**Comment by rafaqz** [comment]
Great. Ping me if you need help with anything. I'm also pretty keen to have this working for my own work.

There is already a static Plots.jl recipe, we just need to add a dynamic recipe for Makie/MakieCore.jl that tracks the Makie plot zoom after plotting.

**Comment by rafaqz** [comment]
Update: we put a package for this together at JuliaEO conference, just with base Makie.jl and MapTiles.jl: 
https://github.com/MakieOrg/Tyler.jl/blob/master/src/Tyler.jl

It can probably be easily adapted to GeoMakie
